apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: oeinnawc1-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:000b5a5742c1d203a4223a9ecd0c0baa66f65fec@sha256:82a4ee8d20028a18e57e21626ff8446d2fd18c2c5db51e683c79442ff2a5530a
          name: container-image
